const ADD_TO_CART = 'ADD_TO_CART';
const DELETE_ITEM = 'DELETE_ITEM';
const GET_PRODUCT_WITH_SAGA = 'GET_PRODUCT_WITH_SAGA';
const GET_PRODUCT_WITH_SAGA_SUCCESS = 'GET_PRODUCT_WITH_SAGA_SUCCESS';
const GET_PRODUCT_WITH_SAGA_FAILED = 'GET_PRODUCT_WITH_SAGA_FAILED';
const INCREASE_COUNT = 'INCREASE_COUNT';
const DECREASE_COUNT = 'DECREASE_COUNT';
const INIT_CART = 'INIT_CART';
const DELETE_ALL_CART = 'DELETE_ALL_CART';
const REFRESH_PRODUCT_LIST = 'REFRESH_PRODUCT_LIST';
export {
  ADD_TO_CART,
  DELETE_ITEM,
  GET_PRODUCT_WITH_SAGA,
  GET_PRODUCT_WITH_SAGA_SUCCESS,
  GET_PRODUCT_WITH_SAGA_FAILED,
  INCREASE_COUNT,
  DECREASE_COUNT,
  INIT_CART,
  DELETE_ALL_CART,
  REFRESH_PRODUCT_LIST,
};
