const NAVIGATION_PREFIX = 'NAVIGATION_';

enum RequestMethod {
  POST = 'POST',
  PATCH = 'PATCH',
  GET = 'GET',
  PUT = 'PUT',
}
export { RequestMethod };
//Navigation
const NAVIGATION_ROOT_WITH_SAGA = 'NAVIGATION_ROOT_WITH_SAGA';
const NAVIGATION_ROOT_SUCCESS = 'NAVIGATION_ROOT_SUCCESS';
const SELECTED_MENU = 'SELECTED_MENU';
const RESET_ALL_STATE = 'RESET_ALL_STATE';
//Menu
const SIDE_MENU = `${NAVIGATION_PREFIX}SIDE_MENU`;
// Loading with saga
const SHOW_LOADING_WITH_SAGA = 'SHOW_LOADING_WITH_SAGA';
const HIDE_LOADING_WITH_SAGA = 'HIDE_LOADING_WITH_SAGA';
const LOADING_PAGE = `${NAVIGATION_PREFIX}LOADING_PAGE`;

export {
  NAVIGATION_ROOT_WITH_SAGA,
  NAVIGATION_ROOT_SUCCESS,
  SELECTED_MENU,
  RESET_ALL_STATE,
  SIDE_MENU,
  SHOW_LOADING_WITH_SAGA,
  HIDE_LOADING_WITH_SAGA,
  LOADING_PAGE,
};
