const NAVIGATION_PREFIX = 'IN_';
export const ROOT = `${NAVIGATION_PREFIX}Root`;
const APP_SCREEN = `${NAVIGATION_PREFIX}APP_SCREEN`;

const SIDE_MENU = `${NAVIGATION_PREFIX}SIDE_MENU`;
const LOADING_SCREEN = `${NAVIGATION_PREFIX}LOADING_SCREEN`;

const HOME_SCREEN = `${NAVIGATION_PREFIX}HOME_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;
const CART_SCREEN = `${NAVIGATION_PREFIX}CART_SCREEN`;

const DRAW_SCREEN = `${NAVIGATION_PREFIX}DRAW_SCREEN`;

export { SIDE_MENU, LOADING_SCREEN, HOME_SCREEN, LOGIN_SCREEN, CART_SCREEN, DRAW_SCREEN, APP_SCREEN };
